/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:37:57 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreUtils.framework&header=CoreTelephonyClientDelegate.h
*/


@protocol CoreTelephonyClientDelegate <NSObject>

@optional
-(void)activeSubscriptionsDidChange;
-(void)subscriptionInfoDidChange;
-(void)simLessSubscriptionsDidChange;
-(void)dualSimCapabilityDidChange;
@end
