/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CoreTelephonyClientRegistrationDelegateInternal.h
*/


@protocol CoreTelephonyClientRegistrationDelegateInternal <NSObject>

@optional
-(void)operatorNameChanged:(id)arg1 name:(id)arg2;
-(void)displayStatusChanged:(id)arg1 status:(id)arg2;
-(void)cellMonitorUpdate:(id)arg1 info:(id)arg2;
-(void)networkReselectionNeeded:(id)arg1;
-(void)cellChanged:(id)arg1 cell:(id)arg2;
-(void)signalStrengthChanged:(id)arg1 info:(id)arg2;
-(void)rejectCauseCodeChanged:(id)arg1 causeCode:(id)arg2;
-(void)plmnChanged:(id)arg1 plmn:(id)arg2;
-(void)enhancedDataLinkQualityChanged:(id)arg1 metric:(id)arg2;
-(void)ratSelectionChanged:(id)arg1 selection:(id)arg2;
-(void)networkSelected:(id)arg1 success:(BOOL)arg2 mode:(id)arg3;
-(void)voiceLinkQualityChanged:(id)arg1 metric:(id)arg2;
-(void)customerServiceProfileChanged:(id)arg1 visible:(BOOL)arg2;
-(void)dataRatesChanged;
-(void)encryptionStatusChanged:(id)arg1 info:(id)arg2;
-(void)enhancedVoiceLinkQualityChanged:(id)arg1 metric:(id)arg2;
-(void)imsRegistrationChanged:(id)arg1 info:(id)arg2;
-(void)networkListAvailable:(id)arg1 list:(id)arg2;
-(void)nrDisableStatusChanged:(id)arg1 status:(id)arg2;
@end
