/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CoreTelephonyClientDataDelegateInternal.h
*/


@protocol CoreTelephonyClientDataDelegateInternal <NSObject>

@optional
-(void)dataStatus:(id)arg1 dataStatusInfo:(id)arg2;
-(void)preferredDataSimChanged:(id)arg1;
-(void)internetConnectionStateChanged:(id)arg1;
-(void)currentDataServiceDescriptorChanged:(id)arg1;
-(void)regDataModeChanged:(id)arg1 dataMode:(int)arg2;
-(void)connectionActivationError:(id)arg1 connection:(int)arg2 error:(int)arg3;
-(void)internetDataStatus:(id)arg1;
-(void)dataSettingsChanged:(id)arg1;
-(void)connectionStateChanged:(id)arg1 connection:(int)arg2 dataConnectionStatusInfo:(id)arg3;
-(void)internetDataStatusBasic:(id)arg1;
-(void)currentDataSimChanged:(id)arg1;
-(void)internetConnectionActivationError:(int)arg1;
-(void)servingNetworkChanged:(id)arg1;
-(void)internetConnectionAvailability:(BOOL)arg1;
-(void)nrSlicedRunningAppStateChanged:(id)arg1;
-(void)tetheringStatus:(id)arg1 connectionType:(int)arg2;
-(void)anbrActivationState:(id)arg1 enabled:(BOOL)arg2;
-(void)anbrBitrateRecommendation:(id)arg1 bitrate:(id)arg2 direction:(int)arg3;
-(void)connectionAvailability:(id)arg1 availableConnections:(id)arg2;
-(void)dataRoamingSettingsChanged:(id)arg1 status:(BOOL)arg2;
-(void)nrSliceAppStateChanged:(id)arg1 status:(BOOL)arg2 trafficDescriptors:(id)arg3;
-(void)preferredDataServiceDescriptorChanged:(id)arg1;
-(void)serviceDisconnection:(id)arg1 status:(id)arg2;
-(void)tetheringStatus:(id)arg1;
@end
