/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:47:17 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/CellularPlanManager.framework/CellularPlanManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 https://www.developer.limneos.net/index.php?ios=17.1&framework=CellularPlanManager.framework&header=CTCellularPlanManager.h
*/


//#import <CellularPlanManager/CellularPlanManager-Structs.h>
#import "CTCellularPlanItem.h"
@class NSXPCConnection, CTCellularPlanManagerDelegate;

@interface CTCellularPlanManager : NSObject {

//    dispatch_queue_sRef _queue;
    NSXPCConnection* _connection;
    CTCellularPlanManagerDelegate* _delegate;
}
+(instancetype)sharedManager;
+(long long)calculateInstallConsentTextTypeFor:(id)arg1 ;
-(void)ping;
-(void)setIMEIPrefix:(id)arg1 ;
-(id)danglingPlanItemsShouldUpdate:(BOOL)arg1 ;
-(void)resolveSimLabel:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)didPurchasePlanForCarrier:(id)arg1 mnc:(id)arg2 gid1:(id)arg3 gid2:(id)arg4 state:(id)arg5 ;
//-(void)planItemsWithCompletion:(/*^block*/id)arg1;
-(void)planItemsWithCompletion:(void (^)(NSArray<CTCellularPlanItem *> *items))completion; // 获取全部蜂窝数据卡
-(id)didSelectPlanForDefaultVoice:(id)arg1 ;
-(void)getSupportedFlowTypes:(/*^block*/id)arg1 ;
-(void)addNewRemotePlanWithAddress:(id)arg1 matchingId:(id)arg2 oid:(id)arg3 confirmationCode:(id)arg4 isPairing:(BOOL)arg5 withCSN:(id)arg6 withContext:(id)arg7 userConsent:(long long)arg8 completion:(/*^block*/id)arg9 ;
-(void)userDidProvideResponse:(long long)arg1 confirmationCode:(id)arg2 forPlan:(id)arg3 isRemote:(BOOL)arg4 completion:(/*^block*/id)arg5 ;
-(void)_connect_sync;
-(void)enterSimSetupWithCompletion:(/*^block*/id)arg1 ;
-(id)synchronousProxyWithErrorHandler:(/*^block*/id)arg1 ;
-(void)deletePlanPendingTransfer:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)setSelectedEnv:(long long)arg1 ;
-(void)latitudeLongitudeOverride:(/*^block*/id)arg1;
-(void)setLatitude:(id)arg1 andLongitude:(id)arg2;
-(void)setRoamingSignupOverride:(BOOL)arg1 ;
-(void)didPurchasePlanForCsn:(id)arg1 iccid:(id)arg2 profileServer:(id)arg3 state:(id)arg4 ;
-(id)resolveSimLabel:(id)arg1 ;
-(id)didEnablePlanItems:(id)arg1 ;
-(void)didSelectPlanForData:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)expirePlan;
-(void)didDeletePlanItem:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)selectRemoteProfile:(id)arg1 ;
-(void)getSelectedEnv:(/*^block*/id)arg1 ;
-(void)setUserInPurchaseFlow:(BOOL)arg1 ;
-(void)getIMEIPrefix:(/*^block*/id)arg1 ;
-(void)didSelectRemotePlanItem:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)mccMncOverride:(/*^block*/id)arg1 ;
-(void)shouldShowAddNewRemotePlanWithContext:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)finishRemoteProvisioningForCSN:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)dealloc;
-(void)didPurchasePlanWithIccid:(id)arg1 downloadProfile:(BOOL)arg2 ;
-(id)getPredefinedLabels;
-(void)didCancelRemotePlan;
-(void)userDidProvideConsentResponse:(long long)arg1 forPlan:(id)arg2 isRemote:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)startProvisioningWithCompletion:(/*^block*/id)arg1 ;
-(void)addNewPlanWithFlowType:(unsigned long long)arg1 completion:(/*^block*/id)arg2 ;
-(void)didTransferPlanForCsn:(id)arg1 iccid:(id)arg2 srcIccid:(id)arg3 profileServer:(id)arg4 state:(id)arg5 ;
-(void)eraseAllRemotePlansWithCompletion:(/*^block*/id)arg1 ;
-(void)setAutoPlanSelection:(BOOL)arg1 ;
-(id)init;
-(void)pendingReleaseRemotePlan;
-(void)getRoamingSignupOverrideWithCompletion:(/*^block*/id)arg1 ;
-(id)getShortLabelsForLabels:(id)arg1 ;
-(void)danglingPlanItemsShouldUpdate:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)didDeleteRemotePlanItem:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)installPendingRemotePlan:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)eraseAllRemotePlansWithCSN:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)didSelectPlansForIMessage:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)didSelectPlanForData:(id)arg1 ;
-(void)shouldShowPlanSetup:(/*^block*/id)arg1 ;
-(void)isRemotePlanCapableWithContext:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)addNewPlanWithCardData:(id)arg1 confirmationCode:(id)arg2 triggerType:(long long)arg3 userConsent:(long long)arg4 completion:(/*^block*/id)arg5 ;
-(void)remapSimLabel:(id)arg1 to:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)activatePlanPendingTransfer:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSkipEligibilityCheck:(/*^block*/id)arg1 ;
-(id)planItemsShouldUpdate:(BOOL)arg1 ;
-(void)startRemoteProvisioningForCSN:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)deleteRemoteProfile:(id)arg1 ;
-(id)cancelPlanActivation:(id)arg1 ;
-(NSString *)getSubscriptionContextUUIDforPlan:(CTCellularPlanItem *) item; // 获取某个卡的所在卡槽位uuid
-(void)setSkipEligibilityCheck:(BOOL)arg1 ;
-(void)didPurchaseRemotePlanForEid:(id)arg1 imei:(id)arg2 meid:(id)arg3 iccid:(id)arg4 alternateSmdpFqdn:(id)arg5 completion:(/*^block*/id)arg6 ;
-(id)setLabelForPlan:(id)arg1 label:(id)arg2 ;
-(void)remotePlanItemsWithUpdateFetch:(BOOL)arg1 withCSN:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_reconnect;
-(void)finishProvisioningWithCompletion:(/*^block*/id)arg1 ;
-(void)deleteAllRemoteProfiles;
-(void)addNewPlanWithAddress:(id)arg1 matchingId:(id)arg2 oid:(id)arg3 confirmationCode:(id)arg4 triggerType:(long long)arg5 userConsent:(long long)arg6 completion:(/*^block*/id)arg7 ;
-(void)carrierItemsShouldUpdate:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)planItemsShouldUpdate:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)manageAccountForRemotePlan:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)remapSimLabel:(id)arg1 to:(id)arg2 ;
-(void)eraseAllPlans:(/*^block*/id)arg1 ;
-(void)_ensureConnected_sync;
-(void)setMcc:(long long)arg1 andMnc:(long long)arg2 ;
-(void)showUiIgnoringActivationFlags:(BOOL)arg1 ;
-(id)getPlansPendingTransferForTestability:(id*)arg1 ;
-(id)getPlansPendingTransfer:(id*)arg1 ;
-(void)fetchRemoteProfiles:(id)arg1 ;
-(void)didSelectPlanItem:(id)arg1 isEnable:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(id)didSelectPlanItem:(id)arg1 isEnable:(BOOL)enable; // 开启或者关闭某张卡
-(void)remotePlanItemsWithCompletion:(/*^block*/id)arg1 ;
-(unsigned long long)getSupportedFlowTypes;
-(void)userSignupInitiatedOrFailed;
-(void)getAutoPlanSelectionWithCompletion:(/*^block*/id)arg1 ;
-(void)resumePlanProvisioning:(BOOL)arg1 userConsent:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)addNewRemotePlanWithCardData:(id)arg1 confirmationCode:(id)arg2 isPairing:(BOOL)arg3 withCSN:(id)arg4 withContext:(id)arg5 userConsent:(long long)arg6 completion:(/*^block*/id)arg7 ;
-(void)getSelectedProxy:(/*^block*/id)arg1 ;
-(void)getPhoneAuthTokenWithMessage:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)exitSimSetupWithCompletion:(/*^block*/id)arg1 ;
-(void)setSelectedProxy:(long long)arg1 ;
-(void)didSelectPlanForDefaultVoice:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getRemoteInfo:(/*^block*/id)arg1 ;
-(void)addNewRemotePlan:(BOOL)arg1 withCSN:(id)arg2 withContext:(id)arg3 userConsent:(long long)arg4 completion:(/*^block*/id)arg5 ;
@end
