/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:47:17 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/CellularPlanManager.framework/CellularPlanManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 https://www.developer.limneos.net/index.php?ios=17.1&framework=CellularPlanManager.framework&header=CTCellularPlan.h
*/

#import <CellularPlanManager/CellularPlanManager-Structs.h>
#import <CellularPlanManager/NSCopying.h>
#import <CellularPlanManager/NSSecureCoding.h>

@class NSString, CTCellularPlanProfile, CTCellularPlanSubscription, NSNumber, NSData, NSArray;

@interface CTCellularPlan : NSObject <NSCopying, NSSecureCoding> {

    BOOL _requiresUserConsent;
    BOOL _isHomePlan;
    NSString* _phoneNumber;
    CTCellularPlanProfile* _profile;
    CTCellularPlanSubscription* _subscription;
    NSNumber* _subscriptionStatusOverride;
}
@property (nonatomic,retain) CTCellularPlanProfile * profile;                        //@synthesize profile=_profile - In the implementation block
@property (nonatomic,retain) CTCellularPlanSubscription * subscription;              //@synthesize subscription=_subscription - In the implementation block
@property (nonatomic,retain) NSNumber * subscriptionStatusOverride;                  //@synthesize subscriptionStatusOverride=_subscriptionStatusOverride - In the implementation block
@property (assign,nonatomic) BOOL isHomePlan;                                        //@synthesize isHomePlan=_isHomePlan - In the implementation block
@property (nonatomic,retain) NSString * phoneNumber;                                 //@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (assign,nonatomic) BOOL requiresUserConsent;                               //@synthesize requiresUserConsent=_requiresUserConsent - In the implementation block
@property (nonatomic,readonly) NSData * profileId;
@property (nonatomic,readonly) BOOL isSelected;
@property (nonatomic,readonly) NSString * iccid;
@property (nonatomic,readonly) BOOL autoRenew;
@property (nonatomic,readonly) double timestamp;
@property (nonatomic,readonly) double billingStartDate;
@property (nonatomic,readonly) double billingEndDate;
@property (nonatomic,readonly) NSString * carrierName;
@property (nonatomic,readonly) int planType;
@property (nonatomic,readonly) NSString * planDescription;
@property (nonatomic,readonly) int planStatus;
@property (nonatomic,readonly) int accountStatus;
@property (nonatomic,readonly) NSString * accountURL;
@property (nonatomic,readonly) BOOL isDisableNotAllowed;
@property (nonatomic,readonly) BOOL isDeleteNotAllowed;
@property (nonatomic,readonly) NSArray * dataUsage;
@property (nonatomic,readonly) int status;
@property (nonatomic,readonly) BOOL isSelectable;
+(BOOL)supportsSecureCoding;
-(int)accountStatus;
-(NSString *)carrierName;
-(BOOL)isSelected;
-(NSString *)phoneNumber;
-(void)setPhoneNumber:(NSString *)arg1 ;
-(id)statusAsString:(id)arg1 ;
-(void)setProfile:(CTCellularPlanProfile *)arg1 ;
-(void)setSubscription:(CTCellularPlanSubscription *)arg1 ;
-(CTCellularPlanProfile *)profile;
-(double)timestamp;
-(NSArray *)dataUsage;
-(void)encodeWithCoder:(id)arg1 ;
-(CTCellularPlanSubscription *)subscription;
-(id)initWithCoder:(id)arg1 ;
-(id)init;
-(BOOL)isSelectable;
-(int)status;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)redactedDescription;
-(NSString *)iccid;
-(int)planStatus;
-(int)planType;
-(NSString *)accountURL;
-(NSData *)profileId;
-(BOOL)requiresUserConsent;
-(void)setRequiresUserConsent:(BOOL)arg1 ;
-(NSString *)planDescription;
-(BOOL)autoRenew;
-(double)billingEndDate;
-(double)billingStartDate;
-(id)initWithProfile:(id)arg1 subscription:(id)arg2 ;
-(BOOL)isDeleteNotAllowed;
-(BOOL)isDisableNotAllowed;
-(BOOL)isHomePlan;
-(long long)planDescriptionCompare:(id)arg1 ;
-(void)setIsHomePlan:(BOOL)arg1 ;
-(void)setSubscriptionStatusOverride:(NSNumber *)arg1 ;
-(NSNumber *)subscriptionStatusOverride;
@end

