/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:47:17 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/CellularPlanManager.framework/CellularPlanManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CellularPlanManager.framework&header=CTCellularPlanItem.h
*/

//#import <CellularPlanManager/CellularPlanManager-Structs.h>
//#import <CellularPlanManager/NSCopying.h>
//#import <CellularPlanManager/NSSecureCoding.h>

@class NSString, CTCellularPlan, CTPlan, CTUserLabel, NSUUID, NSNumber;

@interface CTCellularPlanItem : NSObject <NSCopying, NSSecureCoding> {

    NSString* _name;
    NSString* _iccid;
    BOOL _shouldDisplayType;
    BOOL _shouldAutoSelectWhenInRange;
    BOOL _shouldDisplayExtendedConsentInfo;
    BOOL _isSimStateValid;
    BOOL _isSelectable;
    BOOL _shouldDisplay;
    BOOL _shouldAppearDisabled;
    BOOL _isActiveDataPlan;
    BOOL _isDefaultVoice;
    BOOL _isLocalTransferToeSIMSupported;
    BOOL _isTransferred;
    int _status;
    NSString* _label;
    CTCellularPlan* _plan;
    CTPlan* _ctPlan;
    long long _type;
    long long _lockState;
    long long _transferredStatus;
    NSString* _transferredToDeviceDisplayName;
    unsigned long long _supportedTransferOption;
    long long _settingsMode;
    NSString* _uuid;
    NSString* _phoneNumber;
    CTUserLabel* _userLabel;
    NSUUID* _companionSlotUuid;
    NSString* _companionSimLabelId;
    NSNumber* _isSelectedOverride;
}
@property (nonatomic,retain) NSNumber * isSelectedOverride;                            //@synthesize isSelectedOverride=_isSelectedOverride - In the implementation block
@property (assign,nonatomic) long long type;                                           //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) long long lockState;                                      //@synthesize lockState=_lockState - In the implementation block
@property (assign,nonatomic) BOOL shouldDisplayType;                                   //@synthesize shouldDisplayType=_shouldDisplayType - In the implementation block
@property (assign,nonatomic) BOOL shouldAutoSelectWhenInRange;                         //@synthesize shouldAutoSelectWhenInRange=_shouldAutoSelectWhenInRange - In the implementation block
@property (assign,nonatomic) BOOL isSimStateValid;                                     //@synthesize isSimStateValid=_isSimStateValid - In the implementation block
@property (assign,nonatomic) BOOL isSelectable;                                        //@synthesize isSelectable=_isSelectable - In the implementation block
@property (assign,nonatomic) BOOL shouldAppearDisabled;                                //@synthesize shouldAppearDisabled=_shouldAppearDisabled - In the implementation block
@property (assign,nonatomic) BOOL shouldDisplay;                                       //@synthesize shouldDisplay=_shouldDisplay - In the implementation block
@property (assign,nonatomic) BOOL isActiveDataPlan;                                    //@synthesize isActiveDataPlan=_isActiveDataPlan - In the implementation block
@property (assign,nonatomic) BOOL isDefaultVoice;                                      //@synthesize isDefaultVoice=_isDefaultVoice - In the implementation block
@property (assign,nonatomic) BOOL shouldDisplayExtendedConsentInfo;                    //@synthesize shouldDisplayExtendedConsentInfo=_shouldDisplayExtendedConsentInfo - In the implementation block
@property (assign,nonatomic) BOOL isLocalTransferToeSIMSupported;                      //@synthesize isLocalTransferToeSIMSupported=_isLocalTransferToeSIMSupported - In the implementation block
@property (assign,nonatomic) BOOL isTransferred;                                       //@synthesize isTransferred=_isTransferred - In the implementation block
@property (assign,nonatomic) int status;                                               //@synthesize status=_status - In the implementation block
@property (assign,nonatomic) unsigned long long supportedTransferOption;               //@synthesize supportedTransferOption=_supportedTransferOption - In the implementation block
@property (assign,nonatomic) long long settingsMode;                                   //@synthesize settingsMode=_settingsMode - In the implementation block
@property (nonatomic,copy) NSUUID * companionSlotUuid;                                 //@synthesize companionSlotUuid=_companionSlotUuid - In the implementation block
@property (nonatomic,copy) NSString * companionSimLabelId;                             //@synthesize companionSimLabelId=_companionSimLabelId - In the implementation block
@property (nonatomic,retain) NSString * phoneNumber;                                   //@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,retain) NSString * label;                                         //@synthesize label=_label - In the implementation block
@property (nonatomic,retain) CTUserLabel * userLabel;                                  //@synthesize userLabel=_userLabel - In the implementation block
@property (nonatomic,readonly) NSString * identifier;
@property (nonatomic,readonly) NSString * name;
@property (nonatomic,readonly) CTCellularPlan * plan;                                  //@synthesize plan=_plan - In the implementation block
@property (nonatomic,readonly) CTPlan * ctPlan;                                        //@synthesize ctPlan=_ctPlan - In the implementation block
@property (nonatomic,readonly) BOOL isBackedByCellularPlan;
@property (nonatomic,readonly) BOOL isSelected;
@property (nonatomic,readonly) BOOL isInstalling;
@property (nonatomic,readonly) long long transferredStatus;                            //@synthesize transferredStatus=_transferredStatus - In the implementation block
@property (nonatomic,readonly) BOOL isCheckingCellularConnectivity;
@property (nonatomic,readonly) NSString * transferredToDeviceDisplayName;              //@synthesize transferredToDeviceDisplayName=_transferredToDeviceDisplayName - In the implementation block
@property (nonatomic,readonly) NSString * uuid;                                        //@synthesize uuid=_uuid - In the implementation block
@property (nonatomic,readonly) NSString * iccid;
@property (nonatomic,readonly) NSString * carrierName;
+(BOOL)supportsSecureCoding;
-(NSString *)carrierName;
-(NSString *)uuid;
-(CTCellularPlan *)plan;
-(BOOL)isSelected;
-(NSString *)phoneNumber;
-(void)setPhoneNumber:(NSString *)arg1 ;
-(long long)compare:(id)arg1 ;
-(void)setStatus:(int)arg1 ;
-(long long)type;
-(id)customDescription;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setLabel:(NSString *)arg1 ;
-(void)setLockState:(long long)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)label;
-(BOOL)isSelectable;
-(void)setType:(long long)arg1 ;
-(int)status;
-(NSString *)identifier;
-(id)typeAsString:(long long)arg1 ;
-(long long)lockState;
-(NSString *)name;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)redactedDescription;
-(NSString *)iccid;
-(CTUserLabel *)userLabel;
-(void)setIsSelectable:(BOOL)arg1 ;
-(BOOL)shouldDisplay;
-(BOOL)isInstalling;
-(BOOL)isSimStateValid;
-(void)setShouldAutoSelectWhenInRange:(BOOL)arg1 ;
-(NSString *)companionSimLabelId;
-(NSUUID *)companionSlotUuid;
-(CTPlan *)ctPlan;
-(id)initWithCellularPlan:(id)arg1 uuid:(id)arg2 iccid:(id)arg3 name:(id)arg4 type:(long long)arg5 phoneNumber:(id)arg6 label:(id)arg7 isLocalTransferToeSIMSupported:(BOOL)arg8 isTransferred:(BOOL)arg9 transferredStatus:(long long)arg10 transferredToDeviceDisplayName:(id)arg11 supportedTransferOption:(unsigned long long)arg12 settingsMode:(long long)arg13 ;
-(id)initWithCellularPlan:(id)arg1 uuid:(id)arg2 type:(long long)arg3 phoneNumber:(id)arg4 label:(id)arg5 transferredStatus:(long long)arg6 transferredToDeviceDisplayName:(id)arg7 supportedTransferOption:(unsigned long long)arg8 settingsMode:(long long)arg9 ;
-(id)initWithIccid:(id)arg1 uuid:(id)arg2 name:(id)arg3 phoneNumber:(id)arg4 label:(id)arg5 isLocalTransferToeSIMSupported:(BOOL)arg6 isTransferred:(BOOL)arg7 transferredStatus:(long long)arg8 transferredToDeviceDisplayName:(id)arg9 supportedTransferOption:(unsigned long long)arg10 settingsMode:(long long)arg11 ;
-(BOOL)isActiveDataPlan;
-(BOOL)isBackedByCellularPlan;
-(BOOL)isCheckingCellularConnectivity;
-(BOOL)isDefaultVoice;
-(BOOL)isLocalTransferToeSIMSupported;
-(NSNumber *)isSelectedOverride;
-(BOOL)isTransferred;
-(void)setCompanionSimLabelId:(NSString *)arg1 ;
-(void)setCompanionSlotUuid:(NSUUID *)arg1 ;
-(void)setIsActiveDataPlan:(BOOL)arg1 ;
-(void)setIsDefaultVoice:(BOOL)arg1 ;
-(void)setIsLocalTransferToeSIMSupported:(BOOL)arg1 ;
-(void)setIsSelectedOverride:(NSNumber *)arg1 ;
-(void)setIsSimStateValid:(BOOL)arg1 ;
-(void)setIsTransferred:(BOOL)arg1 ;
-(void)setSettingsMode:(long long)arg1 ;
-(void)setShouldAppearDisabled:(BOOL)arg1 ;
-(void)setShouldDisplay:(BOOL)arg1 ;
-(void)setShouldDisplayExtendedConsentInfo:(BOOL)arg1 ;
-(void)setShouldDisplayType:(BOOL)arg1 ;
-(void)setSupportedTransferOption:(unsigned long long)arg1 ;
-(void)setUserLabel:(CTUserLabel *)arg1 ;
-(long long)settingsMode;
-(id)settingsModeAsString:(long long)arg1 ;
-(BOOL)shouldAppearDisabled;
-(BOOL)shouldAutoSelectWhenInRange;
-(BOOL)shouldDisplayExtendedConsentInfo;
-(BOOL)shouldDisplayType;
-(unsigned long long)supportedTransferOption;
-(long long)transferredStatus;
-(id)transferredStatusAsString:(long long)arg1 ;
-(NSString *)transferredToDeviceDisplayName;
@end

