/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:47:17 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/CellularPlanManager.framework/CellularPlanManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CellularPlanManager.framework&header=CTCellularPlanManagerDelegate.h
*/

#import <CellularPlanManager/CTCellularPlanClientDelegate.h>

@class NSString;

@interface CTCellularPlanManagerDelegate : NSObject <CTCellularPlanClientDelegate>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
-(void)pendingTransferPlanInfoDidUpdate;
-(void)remoteProvisioningDidBecomeAvailable;
-(void)carrierInfoDidUpdate;
-(void)planInfoDidUpdate;
-(void)localPlanInfoDidUpdate:(id)arg1 ;
@end

