/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTPhoneNumberInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSString;

@interface CTPhoneNumberInfo : NSObject <NSCopying, NSSecureCoding> {

    BOOL _isPresent;
    BOOL _isEditable;
    BOOL _isRead;
    NSString* _label;
    NSString* _number;
    NSString* _displayPhoneNumber;
}
@property (nonatomic,retain) NSString * label;                           //@synthesize label=_label - In the implementation block
@property (nonatomic,retain) NSString * number;                          //@synthesize number=_number - In the implementation block
@property (nonatomic,retain) NSString * displayPhoneNumber;              //@synthesize displayPhoneNumber=_displayPhoneNumber - In the implementation block
@property (assign,nonatomic) BOOL isPresent;                             //@synthesize isPresent=_isPresent - In the implementation block
@property (assign,nonatomic) BOOL isEditable;                            //@synthesize isEditable=_isEditable - In the implementation block
@property (assign,nonatomic) BOOL isRead;                                //@synthesize isRead=_isRead - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setIsEditable:(BOOL)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setLabel:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(BOOL)isPresent;
-(BOOL)isEditable;
-(NSString *)label;
-(id)description;
-(NSString *)number;
-(BOOL)isRead;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setNumber:(NSString *)arg1 ;
-(NSString *)displayPhoneNumber;
-(void)setDisplayPhoneNumber:(NSString *)arg1 ;
-(void)setIsPresent:(BOOL)arg1 ;
-(void)setIsRead:(BOOL)arg1 ;
@end
