/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTSupportedMaxDataRates.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSArray;

@interface CTSupportedMaxDataRates : NSObject {

    NSArray* _rates;
}
@property (nonatomic,retain) NSArray * rates;              //@synthesize rates=_rates - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSArray *)rates;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1;
-(id)initWithRates:(id)arg1;
-(void)setRates:(NSArray *)arg1;
@end
