/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTTelephonyNetworkInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/CoreTelephonyClientDataDelegateInternal.h>
//#import <CoreTelephony/CoreTelephonyClientRegistrationDelegateInternal.h>

#import <CoreTelephony/CTTelephonyNetworkInfo.h>
#import "CoreTelephonyClientDataDelegateInternal.h"
#import "CoreTelephonyClientRegistrationDelegateInternal.h"

@protocol CTTelephonyNetworkInfoDelegate;
@class CoreTelephonyClient, CTTelephonyNetworkInfoDelegatePlus, CTServiceDescriptorContainer, NSMutableDictionary, NSString, CTCarrier, NSDictionary;

@interface CTTelephonyNetworkInfo (Private) <CoreTelephonyClientDataDelegateInternal, CoreTelephonyClientRegistrationDelegateInternal>

//@interface CTTelephonyNetworkInfo (Private) <CoreTelephonyClientDataDelegateInternal, CoreTelephonyClientRegistrationDelegateInternal> {
//
//    CoreTelephonyClient* _client;
//    CoreTelephonyClient* _clientPlus;
//    CTTelephonyNetworkInfoDelegatePlus* _delegatePlus;
//    id<CTTelephonyNetworkInfoDelegate> _delegate;
//    /*^block*/id _serviceSubscriberCellularProvidersDidUpdateNotifier;
//    /*^block*/id _subscriberCellularProviderDidUpdateNotifier;
//    BOOL _initialized;
//    BOOL _dataBearerCellularTechnologyInitialized;
//    BOOL _nrFrequencyRangeInitialized;
//    int _cachedDataBearerCellularTechnology;
//    unsigned _cachedNrFrequencyRange;
//    CTServiceDescriptorContainer* _descriptors;
//    NSMutableDictionary* _serviceSubscriberCellularProviders;
//    NSMutableDictionary* _cachedCurrentRadioAccessTechnology;
//    NSMutableDictionary* _cachedSignalStrength;
//    NSMutableDictionary* _cachedCellIds;
////    queue* _clientQueue;
//}
@property (retain) NSMutableDictionary * serviceSubscriberCellularProviders;                           //@synthesize serviceSubscriberCellularProviders=_serviceSubscriberCellularProviders - In the implementation block
@property (retain) NSMutableDictionary * cachedCurrentRadioAccessTechnology;                           //@synthesize cachedCurrentRadioAccessTechnology=_cachedCurrentRadioAccessTechnology - In the implementation block
@property (retain) NSMutableDictionary * cachedSignalStrength;                                         //@synthesize cachedSignalStrength=_cachedSignalStrength - In the implementation block
@property (retain) NSMutableDictionary * cachedCellIds;                                                //@synthesize cachedCellIds=_cachedCellIds - In the implementation block
@property (assign) int cachedDataBearerCellularTechnology;                                             //@synthesize cachedDataBearerCellularTechnology=_cachedDataBearerCellularTechnology - In the implementation block
@property (assign) BOOL dataBearerCellularTechnologyInitialized;                                       //@synthesize dataBearerCellularTechnologyInitialized=_dataBearerCellularTechnologyInitialized - In the implementation block
@property (assign) unsigned cachedNrFrequencyRange;                                                    //@synthesize cachedNrFrequencyRange=_cachedNrFrequencyRange - In the implementation block
@property (assign) BOOL nrFrequencyRangeInitialized;                                                   //@synthesize nrFrequencyRangeInitialized=_nrFrequencyRangeInitialized - In the implementation block
@property (readonly) CTServiceDescriptorContainer * descriptors;                                       //@synthesize descriptors=_descriptors - In the implementation block
//@property (assign) queue* clientQueue;                                                                 //@synthesize clientQueue=_clientQueue - In the implementation block
@property (copy,readonly) NSString * dataServiceIdentifier;
@property (weak) id<CTTelephonyNetworkInfoDelegate> delegate;
@property (retain,readonly) CTCarrier * subscriberCellularProvider;
@property (nonatomic,copy) id serviceSubscriberCellularProvidersDidUpdateNotifier;                     //@synthesize serviceSubscriberCellularProvidersDidUpdateNotifier=_serviceSubscriberCellularProvidersDidUpdateNotifier - In the implementation block
@property (nonatomic,copy) id subscriberCellularProviderDidUpdateNotifier;
@property (nonatomic,retain,readonly) NSDictionary * serviceCurrentRadioAccessTechnology;
@property (nonatomic,retain,readonly) NSString * currentRadioAccessTechnology;
//@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
-(id)initWithClient:(id)arg1 ;
-(void)carrierBundleChange:(id)arg1 ;
-(NSMutableDictionary *)cachedCellIds;
-(NSMutableDictionary *)cachedCurrentRadioAccessTechnology;
-(id)serviceCellId;
-(id)serviceSignalStrength;
-(void)setServiceSubscriberCellularProvidersDidUpdateNotifier:(id)arg1 ;
//-(queue*)clientQueue;
-(NSString *)currentRadioAccessTechnology;
-(void)currentDataServiceDescriptorChanged:(id)arg1 ;
//-(void)setClientQueue:(queue*)arg1 ;
-(void)updateLegacyRat:(id)arg1 ;
-(BOOL)getAllowsVOIP:(BOOL*)arg1 forContext:(id)arg2 withError:(id*)arg3 ;
-(NSDictionary *)serviceCurrentRadioAccessTechnology;
-(void)setServiceSubscriberCellularProviders:(NSMutableDictionary *)arg1 ;
-(void)setServiceSubscriberCellularProviderDidUpdateNotifier:(/*^block*/id)arg1 ;
-(void)updateNrFrequencyRange:(unsigned)arg1 ;
-(void)cellChanged:(id)arg1 cell:(id)arg2 ;
-(id)radioAccessTechnology;
-(void)regDataModeChanged:(id)arg1 dataMode:(int)arg2 ;
-(void)signalStrengthChanged:(id)arg1 info:(id)arg2 ;
-(id)currentNrFrequencyRange;
-(NSMutableDictionary *)serviceSubscriberCellularProviders;
-(void)postNotificationIfReady:(id)arg1 object:(id)arg2 ;
-(void)queryCellIds;
-(void)queryDataBearer;
-(void)queryCTSignalStrength;
-(CTServiceDescriptorContainer *)descriptors;
-(id)subscriberCellularProviderDidUpdateNotifier;
-(void)setCachedNrFrequencyRange:(unsigned)arg1 ;
-(id)serviceSubscriberCellularProvidersDidUpdateNotifier;
-(id)currentDataBearerTechnology;
-(NSMutableDictionary *)cachedSignalStrength;
-(void)dealloc;
-(unsigned)cachedNrFrequencyRange;
-(void)setDataBearerCellularTechnologyInitialized:(BOOL)arg1 ;
-(BOOL)getMobileNetworkCode:(id)arg1 forContext:(id)arg2 withError:(id*)arg3 ;
-(void)tryInitDelegatePlus;
-(void)setDelegate:(id<CTTelephonyNetworkInfoDelegate>)arg1 ;
-(void)dataStatusUpdate:(id)arg1 dataStatusInfo:(id)arg2 ;
-(void)updateCellId:(id)arg1 forDescriptor:(id)arg2 ;
-(id)cellId;
-(BOOL)getCarrierName:(id)arg1 forContext:(id)arg2 withError:(id*)arg3 ;
-(void)queryRatForDescriptor:(id)arg1 ;
-(id)init;
-(void)setCachedCellIds:(NSMutableDictionary *)arg1 ;
-(id<CTTelephonyNetworkInfoDelegate>)delegate;
-(BOOL)nrFrequencyRangeInitialized;
-(void)setCachedDataBearerCellularTechnology:(int)arg1 ;
-(id)signalStrength;
-(void)updateRat:(id)arg1 descriptor:(id)arg2 ;
-(/*^block*/id)serviceSubscribersCellularProviderDidUpdateNotifier;
-(void)queryNrFrequencyRange;
-(void)tryInitNrFrequencyRange;
-(void)setCachedSignalStrength:(NSMutableDictionary *)arg1 ;
-(void)querySignalStrengthForDescriptor:(id)arg1 ;
-(BOOL)getMobileCountryCode:(id)arg1 andIsoCountryCode:(id)arg2 forContext:(id)arg3 withError:(id*)arg4 ;
-(void)updateSignalStrength:(id)arg1 descriptor:(id)arg2 ;
-(CTCarrier *)subscriberCellularProvider;
-(void)setCachedCurrentRadioAccessTechnology:(NSMutableDictionary *)arg1 ;
-(NSString *)dataServiceIdentifier;
-(int)cachedDataBearerCellularTechnology;
-(void)updateDataBearer:(int)arg1 ;
-(void)tryInitPrivateFunctionality;
-(void)setNrFrequencyRangeInitialized:(BOOL)arg1 ;
-(void)setSubscriberCellularProviderDidUpdateNotifier:(id)arg1 ;
-(id)getFirstCellId;
-(BOOL)dataBearerCellularTechnologyInitialized;
-(BOOL)updateNetworkInfoAndShouldNotifyClient:(BOOL*)arg1 forContext:(id)arg2 ;
-(void)tryInitDataBearer;
-(void)queryRat;
@end
